### ISSUE TITLE
Placeholder text is actual text when editing the Feedback Block

### ISSUE THREAD

**Issue by zyousafi** [Automattic/crowdsignal-forms#127]
Site: https://personalplantestsitezyousafi.wordpress.com
Page: Test Page, link to the editor: https://wordpress.com/page/personalplantestsitezyousafi.wordpress.com/2331
Plan: Personal Plan
Screenshot: https://d.pr/i/C2fNAn

When editing the **Feedback Block**, the text I'm pointing to in the screenshot looks like **_placeholder text_** and I think that's what it was meant to be; however, when you click into the box, you have to actually remove the text before you can add in your own message or questions.  This is a little misleading, and it would be better if this was actually **_placeholder text_**

**Comment by digitalwaveride** [comment]
Thanks so much for opening this issue here @zyousafi ! 
Really appreciated!

We discussed it in the team, and while we totally see your point, we were worried that users would not consider this as a place for editing the placeholder text, if it would behave like a placeholder text, and the text would be gone immediately after clicking into the the field. 

As it is in the editor a text that is "persistent", similar to any text label on the site, or the main question of the block, and not (yet) an "input field" (it will become one in the published view) ,we thought it should behave the same way as a text label.

That said, we might raise this issue in some potential upcoming user testing sessions.

Thanks again for pointing us to this!
